name: ci

on:
  push:
    tags:
      - '*-v*'
    paths:
      - 'container-images/**'

env:
  DOCKERHUB_ORG: ${{ github.event.inputs.dockerhub-org || 'bitcoininfrakit' }}
  GITHUB_REPO: 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract image name and version from tag
        id: extract
        run: |
          TAG=${{ github.ref_name }}
          IMAGE_NAME=${TAG%-v*}
          VERSION=${TAG#*-v}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log extracted values
        run: |
          echo "Image Name: ${{ env.IMAGE_NAME }}"
          echo "Version: v${{ env.VERSION }}"

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: container-images/${{ env.IMAGE_NAME }}
          file: container-images/${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:v${{ env.VERSION }}

